### ISSUE TITLE
Occasionally generates things such as "for", "if", etc

### ISSUE THREAD

**Issue by hazel0177** [gehaxelt/PHP-C---JunkCodeGenerator#1]

**Comment by gehaxelt** [comment]
it is supposed to generate those or is there a bug in that? 

Could you elaborate a bit more?

**Comment by hazel0177** [comment]
I meant variable names can end up being named "for", "if" or "do".

**Comment by gehaxelt** [comment]
Hey @hazel0177 , 

does #6 fix the issue?
