### ISSUE TITLE
More junk code

### ISSUE THREAD

**Issue by prooot** [gehaxelt/PHP-C---JunkCodeGenerator#2]
Is there any way having like 5k line of junk code per refresh?

**Comment by gehaxelt** [comment]
No, there is not. 

But you can host a version yourself and adjust the amount of generated junk code :-)

**Comment by prooot** [comment]
Erm is there a simple quick tutorial on how to host myself the same version
as yours but with more junk code?

**Comment by ghost** [comment]
@prooot maybe copy paste main call in a cycle.

**Comment by gehaxelt** [comment]
Yeah, you could do that. 

For hosting it yourself, just upload the repo to your webserver and see `example.php` as said in the README.md. 

If you want more junk code, you should edit the counters in the for loops near https://github.com/gehaxelt/PHP-C---JunkCodeGenerator/blob/master/junkcode.class.php#L60 and https://github.com/gehaxelt/PHP-C---JunkCodeGenerator/blob/master/junkcode.class.php#L72
